/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import java.awt.HeadlessException;
import java.awt.Toolkit;

import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import util.Signup;



/**
 *
 * @author Admin
 */
public class SignIn extends javax.swing.JFrame {
    
    
    int OTP;

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
    }

    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        si = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jusername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 181, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 529, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/robo1.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, -1, 190));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setText("Enter Username");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setText("Enter Password");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 40));

        si.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        si.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sn.png"))); // NOI18N
        si.setText("Sign in ");
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });
        si.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                siKeyPressed(evt);
            }
        });
        jPanel2.add(si, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 122, 27));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Sign Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 122, -1));

        jpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordActionPerformed(evt);
            }
        });
        jpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpasswordKeyPressed(evt);
            }
        });
        jPanel2.add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 220, 40));

        jLabel4.setLabelFor(jLabel4);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 84, -1, 29));
        jPanel2.add(jusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 220, 38));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 143, 46, 44));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 121, -1));

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/12024-200.png"))); // NOI18N
        jButton6.setText("Fogot Password");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Sign In");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/p.jpg"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/username.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 480, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(726, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordActionPerformed
        si.getInputMap().put(KeyStroke.getKeyStroke("ENTER"),"ENTER");// TODO add your handling code here:
    }//GEN-LAST:event_jpasswordActionPerformed

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
        si.getInputMap().put(KeyStroke.getKeyStroke("ENTER"),"ENTER");// TODO add your handling code here:
        String user = jusername.getText();
        /* String after = user.trim();*/
        String pass = String.valueOf(jpassword.getPassword());

        if(user.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Username is Mandotory");
        }

        if(pass.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Password is Mandotory");
        }

        else
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                //ResultSet
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
                String sql = "Select mob from signup where uname=? and pass=?";
                String useraftertrim = user.trim();
                System.out.println(useraftertrim);
                System.out.println(jpassword.getText());

                PreparedStatement pst = (PreparedStatement) con.prepareStatement(sql);
                pst.setString(1,useraftertrim);
                pst.setString(2,jpassword.getText());
                ResultSet rs = pst.executeQuery();

                String mob1=null;

                if(rs.next())
                {
                    mob1 = rs.getString("mob");
                    System.out.println(mob1);
                    System.out.println(rs.next());
                }

                if(mob1!=null)
                {
                    JOptionPane.showMessageDialog(null,"Username/Password Matched");
                    /* try {
                        // Construct data
                        String apiKey = "apikey=" + "wiHdywV5SrM-a68xJQpbZnU2EsmoolXAsrz5K2y1A1";
                        Random rand = new Random();
                        OTP = rand.nextInt(999999);
                        String name = jusername.getText();

                        String message = "&message=" + "Hey " + name+ " Your OTP is " +OTP;
                        String sender = "&sender=" + "Mr Perfect";
                        String numbers = "&numbers=" + (mob1=rs.getString("mob"));
                        String submob = "+" + mob1.substring(0,4) + "*****" + mob1.substring(9);
                        // Send data
                        HttpURLConnection conn = (HttpURLConnection) new URL("https://api.txtlocal.com/send/?").openConnection();
                        String data = apiKey + numbers + message + sender;
                        conn.setDoOutput(true);
                        conn.setRequestMethod("POST");
                        conn.setRequestProperty("Content-Length", Integer.toString(data.length()));
                        conn.getOutputStream().write(data.getBytes("UTF-8"));
                        final BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
                        final StringBuffer stringBuffer = new StringBuffer();
                        String line;
                        while ((line = rd.readLine()) != null) {
                            stringBuffer.append(line);
                        }
                        rd.close();
                        JOptionPane.showConfirmDialog(null,"Otp send Successfully" + submob);

                        //return sResult;
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null,"Error SMS "+e);
                        //return "Error "+e;
                    }

                    */

                    //Close actual window

                    Loading menu = new Loading(user);

                    menu.setUploading();
                    menu.setVisible(true);
                    close();

                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Username/Password is incorrect");
                    jusername.setText(null);
                    jpassword.setText(null);

                }

            }
            catch(ClassNotFoundException | SQLException | HeadlessException e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
        /*
        String username = jusername.getText();
        String password = jpassword.getText();

        if(username.equals("Ashwani") && password.equals("1234"))
        {
            JOptionPane.showMessageDialog(null,"Login Sucessfull");
            jusername.setText(null);
            jpassword.setText(null);

        }
        else
        {
            JOptionPane.showMessageDialog(null,"Invalid Details");
            jusername.setText(null);
            jpassword.setText(null);
        }
        */
    }//GEN-LAST:event_siActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Signup  signup = new Signup();
        signup.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Forgot forgot = new Forgot();
        forgot.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void siKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_siKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_siKeyPressed

    private void jpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
              /*  if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break; */
              UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
                }
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
      
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SignIn().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jusername;
    private javax.swing.JButton si;
    // End of variables declaration//GEN-END:variables

    void setUploading() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
